### ISSUE TITLE
Hosting infrastructure - VLIZ-Parser/FISH

### ISSUE THREAD

**Issue by Denperidge** [osoc21/technical-support#1]
**Is your request related to a problem? Please describe.**
For this project, we're developing an API that has to parse citation strings. It has to run on Docker, for the rest nothing else is specified (at least relevant to hosting).

**Describe the solution you'd like**
Obviously, we'd like to use a free hosting service, so that the API can live a long and healthy life without upkeep costs. After asking in the Discord, I got redirected here to ask about hosting, so here I am!

**Describe alternatives you've considered**
I found a few services that allow for free tiers
- Google Cloud Run
- Heroku
- IBM Cloud
- As well as some Azure/AWS stuff, but I haven't found specific names for those yet

**Additional context**
If there's any advice you can give, whether it be what service to use, how to go about it, or what we _have_ to do, please let me know!

**Comment by jbelien** [comment]
> It has to run on Docker

Is it a requirement from the client ?

> Obviously, we'd like to use a free hosting service, so that the API can live a long and healthy life without upkeep costs.

No worries about the price, Open Knowledge Belgium offers hosting for a year (before being handed over to the client).

>  If there's any advice you can give, whether it be what service to use, how to go about it, or what we have to do, please let me know!

Open Knowledge Belgium uses Digital Ocean.
Once your [Dockerfile](https://docs.docker.com/engine/reference/builder/) is available in [your repository](https://github.com/osoc21/Final-Improved-String-pHarser), ping me (in this issue) and I'll setup an automated deployment for it using [Digital Ocean App Platform](https://www.digitalocean.com/products/app-platform/).

**Comment by Denperidge** [comment]
> Is it a requirement from the client ?

Indeed!

> No worries about the price, Open Knowledge Belgium offers hosting for a year (before being handed over to the client).

Oh that's nice to hear, thanks!

> Open Knowledge Belgium uses Digital Ocean.
Once your Dockerfile is available in your repository, ping me (in this issue) and I'll setup an automated deployment for it using Digital Ocean App Platform.

Oh nice, love DigitalOcean! 
@jbelien Here we are, Dockerfile should hopefully be functional!

**Comment by jbelien** [comment]
Awesome!

I guess it builds and runs.
Could you add a GitHub Actions workflow (see [`docker-image.yml`](https://github.com/actions/starter-workflows/blob/main/ci/docker-image.yml)) to check that the container builds correctly ?
That will also give you the ability to know if there is something wrong with your Dockerfile.

It's a bit early to deploy (and hackathon result is not planned to be deployed).
Ping me again (here) next week when you have a "first" version working and ready to be deployed.

**Comment by Denperidge** [comment]
Hello there! The API should be functional at the moment. I'm sure we're gonna get some weird issues while transferring towards DO, but with a bit of luck we should be okay! @jbelien 
(Oh, and port 5000 has to be reachable if possible!)

**Comment by jbelien** [comment]
Awesome, I'll take care of the deployment ASAP.

>  (Oh, and port 5000 has to be reachable if possible!)

Is there any reason to use the 5000 port instead of a more conventional port ?

**Comment by Denperidge** [comment]
Thankyou!

> Is there any reason to use the 5000 port instead of a more conventional port ?

Currently using 5000 for local testing as well, so mostly for consistency at the moment. When headed towards production a switch to a regular port would indeed be ideal!

**Comment by jbelien** [comment]
Digital Ocean App Platform configuration:
```yaml
name: final-improved-string-pharser
region: ams
services:
- dockerfile_path: Dockerfile
  github:
    branch: master
    repo: osoc21/Final-Improved-String-pHarser
  http_port: 5000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: final-improved-string-pharser
  routes:
  - path: /
  source_dir: /
```

Build/Deployment is on its way.
I'll keep you updated.

**Comment by jbelien** [comment]
🚀 https://final-improved-string-pharser-xxiga.ondigitalocean.app/

Could you check if everything is working ?
If so, I'll enable "Autodeploy code changes".

Does it contain all of your app (frontend + backend) ?

**Comment by Denperidge** [comment]
It should contain everything! However, while the front-end works, the back-end had some issues. Can you try to redeploy? osoc21/Final-Improved-String-pHarser@1ec0460 should have fixed the problem

**Comment by jbelien** [comment]
It has been re-deployed and "Autodeploy code changes" has been enabled.

**Comment by jbelien** [comment]
🚀 https://fish.osoc.be/

**Comment by jbelien** [comment]
Updated Digital Ocean App Platform configuration:
```yaml
domains:
- domain: fish.osoc.be
  type: PRIMARY
  zone: osoc.be
name: final-improved-string-pharser
region: ams
services:
- dockerfile_path: Dockerfile
  github:
    branch: master
    deploy_on_push: true
    repo: osoc21/Final-Improved-String-pHarser
  http_port: 5000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: final-improved-string-pharser
  routes:
  - path: /
  source_dir: /
```
