### ISSUE TITLE
Hosting NodeJS with NestJs Framework

### ISSUE THREAD

**Issue by ezer-i** [osoc21/technical-support#14]
@jbelien Everything works on localhost but then I tried with AWS elasticbeanstalk.
[The AWS link for the project](http://crowdy-server-app.us-east-2.elasticbeanstalk.com/)
![aws elasticbeanstalk](https://user-images.githubusercontent.com/87004888/126155472-e76f75a9-423c-4cdc-9d4f-4e04b5faae8a.PNG)
![aws link response](https://user-images.githubusercontent.com/87004888/126155477-28d0742a-d91b-4a4a-97b0-fd88d37f55fb.PNG)

**Comment by jbelien** [comment]
Hello @osoc21/the-tiny-troop , thanks for reaching out !

OKBE doesn't use AWS Elastic Beanstalk for our infrastructure. So I would recommend not to go that road.

What are your requirements ?

**Comment by ezer-i** [comment]
ooh great thanks for the response,...the environment is NodeJs, Postgres as Database and i have an env file for production if it's relevant.

**Comment by jbelien** [comment]
Perfect! 👌 

Could you bundle everything in a [Dockerfile](https://docs.docker.com/engine/reference/builder/) ?
If so, once the Dockerfile is ready, I'll deploy your project in one click using [DigitalOcean App Platform](https://www.digitalocean.com/products/app-platform/) in our OKBE account.

**EDIT:** If you need the database not to be reset each time you deploy. I can also add a PostgreSQL component in the App Platform (so you don't have to include it in your Dockerfile).

**Comment by jbelien** [comment]
UDATE: I just had a (quick) look at your repository and maybe going through Docker is not needed.

Can you confirm that if we build the backend in `server/` folder with `npm run build` AND we build the frontend in `client/` folder with `yarn build` AND I had a PostgreSQL database component you have everything you need ?

Side note: I see that in `frontend/` you have both `yarn.lock` AND `package-lock.json`. Only **one** of those file should be there depending if you're using yarn or npm. Please delete the file that's not necessary.

**Comment by ezer-i** [comment]
Thanks for the update.
We have corrected our files. we are using yarn and we have removed ``package-lock.json ``and we would like to deploy the server so we can use a single source for frontend (it contains a GraphQL link).

The code for server folder compiles very well but still in development.

We would like the server to be hosted to test our endpoint.

Thank you!

**Comment by jbelien** [comment]
I'll deploy `client/` and `server/` and create a PostgreSQL database tomorrow morning!

**Comment by jbelien** [comment]
Deployment is on its way! I'll let you know (here) when it's ready.

DigitalOcean App Platform configuration:
```yaml
databases:
- engine: PG
  name: crowdy-db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
name: crowdy
region: ams
services:
- build_command: yarn build
  environment_slug: node-js
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${crowdy-db.DATABASE_URL}
  github:
    branch: master
    deploy_on_push: true
    repo: osoc21/Crowdy
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: crowdy
  routes:
  - path: /
  run_command: yarn start:prod
  source_dir: /server
static_sites:
- build_command: yarn build
  environment_slug: node-js
  envs:
  - key: DATABASE_URL
    scope: BUILD_TIME
    value: ${crowdy-db.DATABASE_URL}
  github:
    branch: master
    deploy_on_push: true
    repo: osoc21/Crowdy
  name: crowdy-app
  routes:
  - path: /crowdy-app
  source_dir: /client
```

Questions & Remarks:
- A PostgreSQL 12 instance has been provided. **You can access it using `DATABASE_URL` as environment variable** ; adapt your code accordingly.
- I assumed the client can be build as static website. **Can you confirm ?**
