### ISSUE TITLE
help with first-time shipping 

### ISSUE THREAD

**Issue by AnastasiaDv491** [osoc21/technical-support#15]
**Is your request related to a problem? Please describe.**
not a problem, we jsut want to ship something and not wait until the last week

**Describe the solution you'd like**
server where we can ship

**Describe alternatives you've considered**
Netlify ?

**Comment by jbelien** [comment]
Hello @osoc21/the-deloitted-spaghettis ,

No worries, I've got your back!

What do you need ?
What's your stack ?

**Comment by AnastasiaDv491** [comment]
we need guidance in shipping i believe

**Comment by jbelien** [comment]
No worries ! I'll help you with the shipping ! 😃 

I just need to know what are the "components" you're using in your front-end/back-end to choose the "best" deployment solution.

**Comment by AnastasiaDv491** [comment]
we are using vite project, svelte and tailwind css

back end: flask + python API + docker

**Comment by jbelien** [comment]
Perfect! 👍 

I'll deploy your project using DigitalOcean App Platform:
- Back-end using your `Dockerfile`
- Front-end build statically

**Comment by jbelien** [comment]
Deployment is on its way! I'll let you know (here) when it's ready.

DigitalOcean App Platform configuration:
```yaml
domains:
- domain: future-of-work.osoc.be
  type: PRIMARY
  zone: osoc.be
name: future-of-work
region: ams
services:
- dockerfile_path: /backend/Dockerfile
  github:
    branch: master
    repo: osoc21/Future-of-Work
  http_port: 4000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: future-of-work
  routes:
  - path: /api
  source_dir: /backend
static_sites:
- build_command: npm run build
  environment_slug: node-js
  github:
    branch: master
    repo: osoc21/Future-of-Work
  name: future-of-work-app
  routes:
  - path: /
  source_dir: /frontend
```
